#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const [
  sourcePath,
  rankingPath,
  outputPath,
  rawStartPort,
  rawConverterPath,
  exportDirectory,
  advertiseHost,
] = process.argv.slice(2);

if (!sourcePath || !rankingPath || !outputPath || !rawConverterPath) {
  process.stderr.write(
    'usage: convert-ranking.mjs SOURCE_YAML CURRENT_JSON OUTPUT_YAML START_PORT CONVERTER_JS [EXPORT_DIR ADVERTISE_HOST]\n',
  );
  process.exit(2);
}

const startPort = Number(rawStartPort || 62000);
if (startPort !== 62000) {
  throw new Error('START_PORT must be exactly 62000 for the fixed regional port plan');
}

const converterPath = path.resolve(rawConverterPath);
if (exportDirectory) {
  const exportPath = path.resolve(exportDirectory);
  const dependencies = [
    ['converter', converterPath],
    ['candidate output', path.resolve(outputPath)],
    ...(process.env.CONFIG_PATH
      ? [['CONFIG_PATH', path.resolve(process.env.CONFIG_PATH)]]
      : []),
    ...(process.env.WORK_DIR ? [['WORK_DIR', path.resolve(process.env.WORK_DIR)]] : []),
    ...(process.env.CACHE_DIR ? [['CACHE_DIR', path.resolve(process.env.CACHE_DIR)]] : []),
    ...(process.env.JS_YAML_PATH
      ? [['JS_YAML_PATH', path.resolve(process.env.JS_YAML_PATH)]]
      : []),
    ...String(process.env.NODE_PATH || '')
      .split(path.delimiter)
      .filter(Boolean)
      .map((entry) => ['NODE_PATH', path.resolve(entry)]),
  ];
  const overlaps = (left, right) =>
    left === right || left.startsWith(`${right}${path.sep}`) || right.startsWith(`${left}${path.sep}`);
  for (const [label, dependencyPath] of dependencies) {
    if (overlaps(exportPath, dependencyPath)) {
      throw new Error(`${label} must not overlap EXPORT_DIR: ${dependencyPath}`);
    }
  }
}

const converter = require(converterPath);
const yaml = process.env.JS_YAML_PATH
  ? require(path.resolve(process.env.JS_YAML_PATH))
  : require('js-yaml');
const source = fs.readFileSync(sourcePath, 'utf8');
const current = JSON.parse(fs.readFileSync(rankingPath, 'utf8'));
const outputConfig = converter.convertConfig(yaml.load(source), current, startPort);
const dns = outputConfig && outputConfig.dns;
if (
  !dns ||
  dns.enable !== true ||
  dns.listen !== '127.0.0.1:11553' ||
  dns['enhanced-mode'] !== 'fake-ip' ||
  dns['fake-ip-range'] !== '198.18.0.1/16' ||
  !Array.isArray(dns['default-nameserver']) ||
  dns['default-nameserver'].length === 0 ||
  !Array.isArray(dns.nameserver) ||
  dns.nameserver.length === 0
) {
  throw new Error('converter output must preserve the independent fake-IP DNS configuration');
}
const allowedKeys = new Set();
for (const region of Object.values(current.regions || {})) {
  for (const entry of Object.values(region && region.stable_slots || {})) {
    const key = typeof entry === 'string' ? entry : entry && (entry.node_key || entry.nodeKey || entry.key);
    if (key) allowedKeys.add(String(key));
  }
  for (const entry of region && Array.isArray(region.ranked) ? region.ranked : []) {
    const key = typeof entry === 'string' ? entry : entry && (entry.node_key || entry.nodeKey || entry.key);
    if (key) allowedKeys.add(String(key));
  }
}
if (allowedKeys.size > 0 && (!Array.isArray(outputConfig.listeners) || outputConfig.listeners.length === 0)) {
  throw new Error(`inventory has zero matches for ${allowedKeys.size} allowed node(s)`);
}
const output = yaml.dump(outputConfig);

fs.writeFileSync(outputPath, output, { encoding: 'utf8', mode: 0o600 });

if (exportDirectory) {
  if (!advertiseHost) throw new Error('ADVERTISE_HOST is required with EXPORT_DIR');
  fs.mkdirSync(exportDirectory, { recursive: true, mode: 0o700 });

  const linesByRegion = new Map(
    converter.REGION_PORT_BLOCKS.map((region) => [region.key, []]),
  );
  for (const listener of outputConfig.listeners || []) {
    const region = converter.REGION_PORT_BLOCKS.find((candidate) =>
      String(listener.name).startsWith(`mixed-${candidate.key}-`),
    );
    if (!region) continue;
    const name = String(listener.proxy).replace(/[\r\n]+/g, ' ').trim();
    linesByRegion
      .get(region.key)
      .push(`socks5://${advertiseHost}:${listener.port}{${name}}`);
  }

  for (const [region, lines] of linesByRegion) {
    const content = lines.length > 0 ? `${lines.join('\n')}\n` : '';
    fs.writeFileSync(path.join(exportDirectory, `${region}.txt`), content, {
      encoding: 'utf8',
      mode: 0o600,
    });
  }
  const allLines = [];
  for (const region of converter.REGION_PORT_BLOCKS) {
    allLines.push(...linesByRegion.get(region.key));
  }
  fs.writeFileSync(
    path.join(exportDirectory, 'all.txt'),
    allLines.length > 0 ? `${allLines.join('\n')}\n` : '',
    { encoding: 'utf8', mode: 0o600 },
  );
  fs.writeFileSync(
    path.join(exportDirectory, 'README.txt'),
    `Generated by node-health ranking ${current.version}\nStable slots keep fixed ports; dynamic nodes follow them.\n`,
    { encoding: 'utf8', mode: 0o600 },
  );
}
